[package]
name = "day10"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
failure="0.1"
util = {path="../util"}
regex = "1"
lazy_static = "1"
itertools="0.8"
