[package]
name = "day02"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
counter = "0.4"
day01 = { path = "../day01" }
failure = "0.1"
itertools = "0.7.11"
