[package]
name = "day04"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

[dependencies]
chrono = "0.4"
util = { path = "../util" }
failure = "0.1"
failure_derive = "0.1"
itertools = "0.7"
text_io = "0.1"
