[package]
name = "day05"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

[dependencies]
failure = "0.1"
intrusive-collections = "0.7.8"
util = { path = "../util" }
